apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  selector:
    matchLabels:
      app: portfolio
  replicas: 2   #run 2 pods 
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name:  portfolio
        image: simadock/portfolio-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80